//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALCmisofertas
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMUNA
    {
        public COMUNA()
        {
            this.CONSUMIDOR = new HashSet<CONSUMIDOR>();
            this.SUCURSAL = new HashSet<SUCURSAL>();
        }
    
        public decimal ID { get; set; }
        public string NOMBRE { get; set; }
        public decimal REGION_ID { get; set; }
    
        public virtual REGION REGION { get; set; }
        public virtual ICollection<CONSUMIDOR> CONSUMIDOR { get; set; }
        public virtual ICollection<SUCURSAL> SUCURSAL { get; set; }
    }
}
