//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALCmisofertas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSUMIDOR
    {
        public CONSUMIDOR()
        {
            this.VALORACION = new HashSet<VALORACION>();
            this.COMPORTAMIENTO_BI = new HashSet<COMPORTAMIENTO_BI>();
        }
    
        public string RUN { get; set; }
        public string P_NOMBRE { get; set; }
        public string S_NOMBRE { get; set; }
        public string APELLIDO_P { get; set; }
        public string APELLIDO_M { get; set; }
        public string EMAIL { get; set; }
        public string CLAVE { get; set; }
        public decimal PUNTAJE { get; set; }
        public string ACTIVO { get; set; }
        public string SUSCRITO { get; set; }
        public decimal COMUNA_ID { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        public virtual ICollection<VALORACION> VALORACION { get; set; }
        public virtual ICollection<COMPORTAMIENTO_BI> COMPORTAMIENTO_BI { get; set; }
    }
}
