//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALCmisofertas
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCARGADO
    {
        public ENCARGADO()
        {
            this.OFERTA = new HashSet<OFERTA>();
        }
    
        public string RUN { get; set; }
        public string P_NOMBRE { get; set; }
        public string S_NOMBRE { get; set; }
        public string APELLIDO_P { get; set; }
        public string APELLIDO_M { get; set; }
        public string CLAVE { get; set; }
        public string ACTIVO { get; set; }
        public string RETAIL_RUT { get; set; }
    
        public virtual RETAIL RETAIL { get; set; }
        public virtual ICollection<OFERTA> OFERTA { get; set; }
    }
}
