//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALCmisofertas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesMO : DbContext
    {
        public EntitiesMO()
            : base("name=EntitiesMO")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMINISTRADOR> ADMINISTRADOR { get; set; }
        public DbSet<CATEGORIA> CATEGORIA { get; set; }
        public DbSet<COMUNA> COMUNA { get; set; }
        public DbSet<CONSUMIDOR> CONSUMIDOR { get; set; }
        public DbSet<ENCARGADO> ENCARGADO { get; set; }
        public DbSet<EVALUACION> EVALUACION { get; set; }
        public DbSet<GERENTE> GERENTE { get; set; }
        public DbSet<MARCA> MARCA { get; set; }
        public DbSet<OFERTA> OFERTA { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<RETAIL> RETAIL { get; set; }
        public DbSet<SUCURSAL> SUCURSAL { get; set; }
        public DbSet<VALORACION> VALORACION { get; set; }
        public DbSet<COMPORTAMIENTO_BI> COMPORTAMIENTO_BI { get; set; }
    }
}
