//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALCmisofertas
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFERTA
    {
        public OFERTA()
        {
            this.VALORACION = new HashSet<VALORACION>();
            this.COMPORTAMIENTO_BI = new HashSet<COMPORTAMIENTO_BI>();
        }
    
        public decimal ID { get; set; }
        public string TITULO { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_TERMINO { get; set; }
        public decimal PRECIO_NORMAL { get; set; }
        public decimal PRECIO_OFERTA { get; set; }
        public decimal COMPRA_MIN { get; set; }
        public decimal COMPRA_MAX { get; set; }
        public string ACTIVA { get; set; }
        public string ENCARGADO_RUN { get; set; }
        public byte[] IMAGEN { get; set; }
        public string PRODUCTO_SKU { get; set; }
    
        public virtual ENCARGADO ENCARGADO { get; set; }
        public virtual ICollection<VALORACION> VALORACION { get; set; }
        public virtual PRODUCTO PRODUCTO1 { get; set; }
        public virtual ICollection<COMPORTAMIENTO_BI> COMPORTAMIENTO_BI { get; set; }
    }
}
