//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALCmisofertas
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.OFERTA1 = new HashSet<OFERTA>();
        }
    
        public string SKU { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal CATEGORIA_ID { get; set; }
        public decimal MARCA_ID { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual MARCA MARCA { get; set; }
        public virtual ICollection<OFERTA> OFERTA1 { get; set; }
    }
}
