//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALCmisofertas
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETAIL
    {
        public RETAIL()
        {
            this.ENCARGADO = new HashSet<ENCARGADO>();
            this.SUCURSAL = new HashSet<SUCURSAL>();
        }
    
        public string RUT { get; set; }
        public string RAZON_SOCIAL { get; set; }
    
        public virtual ICollection<ENCARGADO> ENCARGADO { get; set; }
        public virtual ICollection<SUCURSAL> SUCURSAL { get; set; }
    }
}
