//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALCmisofertas
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUCURSAL
    {
        public decimal ID { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public decimal COMUNA_ID { get; set; }
        public string RETAIL_RUT { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        public virtual RETAIL RETAIL { get; set; }
    }
}
